config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :breeds, only: %i[index show]
  resources :cart, only: %i[create destroy]
  resources :horses, only: :show do
    collection do
      get :search
    end
  end

  root to: 'breeds#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :horses
end

app/models/horse.rb
class Horse < ApplicationRecord
  belongs_to :breed
  has_one_attached :image
  validates :name, :top_speed, :number_of_legs, :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :initialize_session
  helper_method :cart

  private

  def initialize_session
    session[:shopping_cart] ||= []
  end

  def cart
    Horse.find(session[:shopping_cart])
  end
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  # GET /
  # GET /breeds
  def index
    @breeds = Breed.order(:name)
    session[:visit_count] ||= 0
    session[:visit_count] += 1
    @visit_count = session[:visit_count]
  end

  # GET /breeds/:id
  def show
    @breed = Breed.find(params[:id])
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    logger.debug("Adding #{params[:id]} to cart")
    id = params[:id].to_i

    unless session[:shopping_cart].include?(id)
      session[:shopping_cart] << id
      horse = Horse.find(id)
      flash[:notice] = " #{horse.name} added to cart."
    end

    redirect_to root_path
  end

  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    horse = Horse.find(id)
    redirect_to root_path
    flash[:notice] = " #{horse.name} removed from cart."
  end
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  # GET /horses/:id
  def show
    @horse = Horse.find(params[:id])
  end

  # GET /horses/search?keywords=user+search+terms
  def search
    @horses = Horse.where("name LIKE ?", "%#{params[:search_term]}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/breeds/index.html.erb
<h3 class="title is-4">All Horse Breeds</h3>

<% @breeds.each do |breed| %>
  <p><%= link_to breed.name, breed %></p>
<% end %>

app/views/breeds/show.html.erb
<h3 class="title is-4"><%= @breed.name %></h3>

<h4 class="title is-5">Horses of this breed</h4>

<div class="columns is-multiline">
  <%= render partial: 'horses/horse',
             collection: @breed.horses,
             locals: { show_link: true } %>
</div>

app/views/horses/_horse.html.erb
<div class="column">
  <div class="card">

    <%# <%= form_with url:cart_index_path, method: :post do %> %>

      <div class="card-content">
        <p class="title">
          <% if show_link %>
            <%= link_to horse.name, horse %>
          <% else %>
            <%= horse.name %>
          <% end %>
        </p>

        <p>Breed: <%= link_to horse.breed.name, horse.breed %></p>
        <% if horse.image.present? %>
          <%# <%= image_tag horse.image %>
          <%= image_tag horse.image.variant(resize_to_limit: [285, 285]).processed %>
        <% end %>
      </div>
      <footer class="card-footer">
        <p class="card-footer-item">
          Age: <br><%= horse.age %>
        </p>
        <p class="card-footer-item">
          Legs: <br><%= horse.number_of_legs %>
        </p>
        <p class="card-footer-item">
          Speed: <br><%= horse.top_speed.round(2) %>
        </p>
        <%= hidden_field_tag(:id,horse.id) %>
        <% if cart.include?(horse) %>
          <%= button_to cart_path(horse), method: :delete do %>
            Remove from cart
          <% end %>
        <% else %>
          <%= form_with url: cart_index_path, method: :post do %>
            <%= hidden_field_tag(:id,horse.id) %>
            <%= button_tag 'Add to cart ✅' %>
          <% end %>
        <% end %>

      </footer>
    </div>
  <%# <% end %> %>
</div>

app/views/horses/search.html.erb
<p>
  Found <%= pluralize(@horses.size, 'result') %>
  for the search term "<%= params[:search_term] %>".
</p>

<div class="search-results columns is-multiline">
  <%= render partial: 'horses/horse',
             collection: @horses,
             locals: { show_link: true } %>
</div>

app/views/horses/show.html.erb
<div class="columns">
  <%= render partial: 'horse',
             object: @horse,
             locals: { show_link: false } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Horses</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>

  <body>
  <section class="section">
    <div class="container">
      <header>
        <h1 class="title is-1"><%= link_to 'Horses on Rails', root_path %></h1>
        <h2 class="subtitle is-4">Look at all the pretty horses standing in a <strong>row, row, row</strong>.</h2>
                  <%# <p>You have <%= pluralize cart.count, 'items' %> in your cart.</p> %>
      <%# <%= debug session[:shopping_cart]%>
      <%= link_to image_tag("HowToGit.jpg", width:250), root_path %>
      <ul>
        <li>Cart</li>
        <% if cart.present? %>
          <sup><%= cart.size %></sup>
          <ul>
            <% cart.each do |horse| %>
              <%= horse.name %><%= button_to '➖', cart_path(horse.id), method: :delete %>
            <% end %>
          </ul>
        <% end %>
      </ul>
      </header>
      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>
      <%= render partial: 'shared/search_form' %>
      <%= yield %>
    </div>
  </section>
  </body>
</html>

app/views/shared/_search_form.html.erb
<%= form_with(url: search_horses_path, local: true, method: "get", class: 'mt-5 mb-5') do %>
  <div class="field has-addons">
    <div class="control">
      <%= text_field_tag(:search_term, nil, class: 'input', placeholder: 'Search Horses By Name') %>
    </div>
    <div class="control">
      <%= submit_tag("Search", class: "button is-info") %>
    </div>
  </div>
<% end %>